### ISSUE TITLE
Using ssl_bridge results in "encrypted" message in Psi

### ISSUE THREAD

**Issue by ghost** [kontalk/client-adapters#5]
Hello!

I have installed all needed deps for python to run ssl_bridge.py, then I pulled it from your repository.

I transferred kontalk-login.crt and kontalk-login.key from kontalk-keys.zip from sdcard of my phone.

I setup Psi so it does not use encryption at all, does plain auth and connects to localhost:5224.

I run ssl_bridge.py as:

./ssl_bridge.py --domain beta.kontalk.net -c kontalk-login.crt -k kontalk-login.key beta.kontalk.net:5222

I verified it connects when Psi logs in.

I see a friend in my roster and I am able to publish and retrieve vcard (defaults to empty)

However each time friend writes a message, I receive not a message but "(encrypted)" translated to Russian "(зашифровано)", so I am unable to read messages.

What I really had missed?

**Comment by daniele-athome** [comment]
You configured everything right. However, Kontalk encryption is not supported by Psi (our plugin is only for Pidgin). Unfortunately there isn't service discovery for this yet, so the Android client will send you encrypted messages anyway, unless he/she disables encryption from settings.
