### ISSUE TITLE
no decryption on pidgin

### ISSUE THREAD

**Issue by freddii** [kontalk/client-adapters#6]
maybe only my bugs or bugs for everyone:
bugs from pidgin to a phone:
*conversation is not crypted from pidgin to a phone account
*the phone account gets an empty message before and after the real message
bugs from a phone to pidgin:
*pidgin gets only the message “(20:10:44) long-hash: (verschlüsselt)”

so it is only possible to send readable message from pidgin to a phone.
i have setup it on pc like this:
https://fredfire1.wordpress.com/2015/07/09/install-kontalk-on-debian-debian/

**Comment by daniele-athome** [comment]
That tutorial refers to bugs in previous versions of the plugin. Please follow this tutorial with the latest version of both the bridge script and Pidgin plugin: https://github.com/kontalk/client-adapters/wiki/Configure-Pidgin-for-Kontalk
Feel free to reopen this issue if it still doesn't work.

**Comment by freddii** [comment]
maybe it is a problem of my kontalk-private.asc
when i import it with gpg --import kontalk-private.asc
i can not list it with gpg --list-key
i can only list it with gpg --list-secret-key

**Comment by daniele-athome** [comment]
I don't understand, did it work when you followed our tutorial?
By the way, try to also import the public part:

```
gpg --import kontalk-public.asc
```

**Comment by freddii** [comment]
i  "fixed" it with disabling encryption on phone.
menu ->settings -> privacy settings -> deactivate encrypt messages
now i can read messages from phone on pidgin-computer

**Comment by daniele-athome** [comment]
That's because decryption is off. It should work with encryption on. If you describe the steps and the problem exactly I can help you.

**Comment by freddii** [comment]
freddii@debian:~$ cd
freddii@debian:~$ mkdir kontalk
freddii@debian:~$ cd ~/kontalk/
freddii@debian:~/kontalk$ cd ~/kontalk/
freddii@debian:~/kontalk$ wget https://raw.githubusercontent.com/kontalk/client-adapters/master/tunnel/ssl_bridge.py
--2015-07-13 13:38:24--  https://raw.githubusercontent.com/kontalk/client-adapters/master/tunnel/ssl_bridge.py
Auflösen des Hostnamen »raw.githubusercontent.com (raw.githubusercontent.com)«... 185.31.17.133
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 5765 (5,6K) [text/plain]
In »»ssl_bridge.py«« speichern.

ssl_bridge.py       100%[=====================>]   5,63K  --.-KB/s   in 0s     

2015-07-13 13:38:24 (81,5 MB/s) - »»ssl_bridge.py«« gespeichert [5765/5765]

freddii@debian:~/kontalk$ chmod 755 ssl_bridge.py
freddii@debian:~/kontalk$ 
freddii@debian:~/kontalk$ cd ~/kontalk/
freddii@debian:~/kontalk$ git clone https://github.com/kontalk/client-adapters.git
Klone nach 'client-adapters'...
remote: Counting objects: 208, done.
remote: Total 208 (delta 0), reused 0 (delta 0), pack-reused 208
Empfange Objekte: 100% (208/208), 32.51 KiB | 0 bytes/s, Fertig.
Löse Unterschiede auf: 100% (95/95), Fertig.
Prüfe Konnektivität... Fertig.
freddii@debian:~/kontalk$ cd ~/kontalk/client-adapters/pidgin
freddii@debian:~/kontalk/client-adapters/pidgin$ make install
gcc -c -Wall -fPIC -DPACKAGE_NAME=\""kontalk"\" -DPACKAGE_VERSION=\""0.1"\" -DENABLE_NLS -DGETTEXT_PACKAGE=\""kontalk"\" -DLOCALEDIR=\"""/usr"/locale"\" -D_FILE_OFFSET_BITS=64 `pkg-config --cflags pidgin` `gpgme-config --cflags` -o gpg.o gpg.c
gcc -c -Wall -fPIC -DPACKAGE_NAME=\""kontalk"\" -DPACKAGE_VERSION=\""0.1"\" -DENABLE_NLS -DGETTEXT_PACKAGE=\""kontalk"\" -DLOCALEDIR=\"""/usr"/locale"\" -D_FILE_OFFSET_BITS=64 `pkg-config --cflags pidgin` `gpgme-config --cflags` -o cpim.o cpim.c
gcc -c -Wall -fPIC -DPACKAGE_NAME=\""kontalk"\" -DPACKAGE_VERSION=\""0.1"\" -DENABLE_NLS -DGETTEXT_PACKAGE=\""kontalk"\" -DLOCALEDIR=\"""/usr"/locale"\" -D_FILE_OFFSET_BITS=64 `pkg-config --cflags pidgin` `gpgme-config --cflags` -o kontalk.o kontalk.c
gcc -shared -fPIC `pkg-config --libs pidgin` `gpgme-config --libs` -o kontalk.so gpg.o cpim.o kontalk.o
install kontalk.so ~/.purple/plugins
freddii@debian:~/kontalk/client-adapters/pidgin$ cd ~/kontalk/
freddii@debian:~/kontalk$ git clone https://github.com/kontalk/pidgin-xmpp-receipts.git
Klone nach 'pidgin-xmpp-receipts'...
remote: Counting objects: 44, done.
remote: Total 44 (delta 0), reused 0 (delta 0), pack-reused 44
Entpacke Objekte: 100% (44/44), Fertig.
Prüfe Konnektivität... Fertig.
freddii@debian:~/kontalk$ cd ~/kontalk/pidgin-xmpp-receipts
freddii@debian:~/kontalk/pidgin-xmpp-receipts$ make
gcc xmpp-receipts.c -O2 -Wall -fpic -g `pkg-config --cflags gtk+-2.0 pidgin` -shared -o xmpp-receipts.so

---

copied by hand the xmpp-receipts.so from /home/freddii/kontalk/pidgin-xmpp-receipts to /home/freddii/.purple/plugins***

---

freddii@debian:~/kontalk/pidgin-xmpp-receipts$ cd .. 
freddii@debian:~/kontalk$ gpg --import kontalk-private.asc
gpg: Schlüssel EB213333: geheimer Schlüssel importiert
gpg: Anzahl insgesamt bearbeiteter Schlüssel: 1
gpg:              gelesene geheime Schlüssel: 1
gpg:            geheime Schlüssel importiert: 1
freddii@debian:~/kontalk$ gpg --import kontalk-public.asc
gpg: Schlüssel EB213333: Öffentlicher Schlüssel "k-test long-hash@beta.kontalk.net" importiert
gpg: Anzahl insgesamt bearbeiteter Schlüssel: 1
gpg:                              importiert: 1  (RSA: 1)
gpg: keine uneingeschränkt vertrauenswürdigen Schlüssel gefunden
freddii@debian:~/kontalk$ gpg --list-key
/home/freddii/.gnupg/pubring.gpg

pub   2048R/EB213333 2015-07-09
uid                  k-test long-hash@beta.kontalk.net
sub      0E/FA15EEEE 2015-07-09
sub      0e/D8878000 2015-07-09

freddii@debian:~/kontalk$ gpg --list-secret-key
/home/freddii/.gnupg/secring.gpg

sec   2048R/EB213333 2015-07-09
uid                  k-test long-hash@beta.kontalk.net
ssb      0E/FFFFFFFF 2015-07-09
ssb      0e/FFFFFFFF 2015-07-09

---

started pidgin and activated the kontalk.so and xmpp-receipts.so plugins **

---

http://imgur.com/HHVnG5N (enable xmpp)
http://imgur.com/aTggTvB (enable kontalk)
http://imgur.com/8ASpW7o (kontalk long hash)

---

added a new pidgin account

---

account setup: http://imgur.com/JKkiglN
account setup advanced: http://imgur.com/jusNPYZ
account ready: http://imgur.com/e0D42B9

freddii@debian:~/kontalk$ ./ssl_bridge.py -d -p 5224 --domain beta.kontalk.net -c kontalk-login.crt -k kontalk-login.key beta.kontalk.net:5222
listening on port 5224, forwarding to beta.kontalk.net:5222
got connection from IPv4Address(TCP, '127.0.0.1', 60940)
connecting to beta.kontalk.net:5222

---

started chatting using encrytion on phone:
http://imgur.com/Rd2wF9x

---

**Comment by daniele-athome** [comment]
The number you need to copy into Kontalk Pidgin plugin settings is the key ID:

```
EB213333
```

Not the long hash before the @beta.kontalk.net.

**Comment by freddii** [comment]
freddii@debian:~$ gpg2 --version
gpg (GnuPG) 2.0.26
libgcrypt 1.6.3

maybe it is a problem cause i have not the latest gnupg version.

**Comment by daniele-athome** [comment]
That also might be a problem with users who registered a new key recently. You need at least GnuPG 2.1.3.
