### ISSUE TITLE
provide hkp interface to download public keys

### ISSUE THREAD

**Issue by pravi** [kontalk/client-adapters#8]
this would improve the xmpp compatibility as openkeychain/conversations will be able to encrypt messages to kontalk users. Also allow manual import of public keys or better OpenKeyChain integration to encrypt messages back to conversations.

**Comment by daniele-athome** [comment]
Despite Kontalk public keys are "public" they still contain sensitive information which not all users are willing to publish, so I will not allow a hkp server out of a Kontalk public keys database, sorry.
Besides, Kontalk public keys are meant to be deployed through XMPP: Conversations (as well as other clients) can and should use public key publishing via the dedicated XEPs.
OpenKeyChain integration is under consideration in another issue but hasn't been decided yet.

**Comment by pravi** [comment]
Which XEP is this? I can't fetch keys from conversations. Two conversations users can use keys, so they have implemented it.

On 2015, നവംബർ 22 9:28:39 PM IST, Daniele Ricci notifications@github.com wrote:

> Despite Kontalk public keys are "public" they still contain sensitive
> information which not all users are willing to publish, so I will not
> allow a hkp server out of a Kontalk public keys database, sorry.
> Besides, Kontalk public keys are meant for to be deployed through XMPP:
> Conversations (as well as other clients) can and should use public key
> publishing via the dedicated XEPs.
> OpenKeyChain integration is under consideration in another issue but
> hasn't been decided yet.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kontalk/client-adapters/issues/8#issuecomment-158770909

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pravi** [comment]
![tmp_2700-screenshot_2015-11-23-09-58-08-173078337](https://cloud.githubusercontent.com/assets/708222/11330130/9d86fea2-91cb-11e5-8d41-21fe7ec6d770.png)

Also kontalk can't find the key even though conversations publish it and other conversations users can find it.

**Comment by daniele-athome** [comment]
Conversations doesn't retrieve the key. I've looked in the source code, it extracts the key ID from the signed presence (which is not exactly wrong per se), but I use public key publishing: http://xmpp.org/extensions/xep-0189.html

With assistance of the server (servers keep the keys and will reply to requests on behalf of the client).
It seems a more correct approach IMHO.
However, I have to say that verifying a signature can help with trusting the owner the key having the private part. But in my case the server handles the keys (and verification will be carried out in messages anyway).

**Comment by pravi** [comment]
Currently conversations use http://xmpp.org/extensions/xep-0027.html and I have asked conversations developers if they are willing to implement xep 0189.

**Comment by pravi** [comment]
@daniele-athome do you use pep for publishing?

**Comment by daniele-athome** [comment]
We don't. We use a direct IQ for requesting the key to the server for the moment. But we will comply to PEP eventually (support for pubsub in Tigase is scarse if not even absent).

**Comment by daniele-athome** [comment]
However, I have to say direct IQ requests for the key are supported by XEP-0189, par. "7. Requesting a Public Key Directly".

**Comment by pravi** [comment]
@iNPUTmice "praveen: what message format are the using?"

@daniele-athome, can you come to conversations@conference.siacs.eu muc?

It would be great if you can answer their questions so they can implement xep 0189.

**Comment by daniele-athome** [comment]
At the moment I can't be present sorry, maybe tonight.

Anyway I only use direct IQs, as specified by par. 7. However the key is returned by the server on behalf of the user.

Another important thing to note is that you can't retrieve the public key if you don't have a subscription to that user.
Also, to help identifying users, the public key is automatically attached in presence stanzas with type=subscribe: https://github.com/kontalk/specs/blob/master/publickey.md (this is useful to give a chance to the other user to know who is requesting a subscription). This last part is not included in XEP-0189 though.
